services:

  mongodb:
    image: mongodb/mongodb-community-server:latest
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-vol:/data/db

volumes:
  mongodb-vol