services:
  redis:
    image: redis/redis-stack:latest
    hostname: redis
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-vol:/data

volumes:
  redis-vol
